### PR TITLE
Implement stricter approve/reject UI

### LINKED ISSUE #73: Selective release and rejection of outputs
Output checkers need to be able to approve a subset of outputs for release. Outputs that are not to be released will be "rejected".

This issue introduces selection of individual outputs for approval and rejection. It does not include JSON metadata describing the rejection, that will follow in a later issue.

This issue is complete when:

- [ ] The output checker can individually select "approve" or "reject" for each output.
- [ ] The "Approve and download" button is renamed to "Release and download".
- [ ] It's not possible to click the "Release and download" button until each output has been explicitly approved or rejected.
- [ ] The output checker gets sufficient feedback from the UI that they understand why they can't click the "Release and download" button.
- [ ] It's possible for the output checker to change their mind about an output after they select "approve" or "reject" (including resetting to the initial null state).
- [x] The zipfile downloaded contains all approved outputs and no rejected outputs.
- [x] If all outputs are rejected then it's not possible to click the "Release and download" button (and feedback is given so the output checker understands why).

### PR DESCRIPTION
**Pull request by bloodearnest**
Fixes #73

### CODE REVIEW

**Comment by bloodearnest** [comment]
> Nothing stands out in the JS +1
> 
> Reading through #73 we're missing a couple of points:
> 
> 1. The output checker gets sufficient feedback from the UI that they understand why they can't click the "Release and download" button.
> 2. It's possible for the output checker to change their mind about an output after they select "approve" or "reject" (including resetting to the initial null state).

Huh, I had missed the brackets there.

 
> For 1 a tooltip would be fine I should think. I'm not sure how easy those would be to implement with the stack in this project but having them in job-server has been really useful for this sort of thing. If they're a pain to add then I think we just leave this as is.

Yep, will add.

> 
> For 2 I think we should add a little more UI feedback to the user:
> 
> * grey out the option not selected

But what if they click it then change their minds?

> * add a reset button to undo a selection

I am not convinced by this requirement, tbh. :thinking:

But it's there so I'll add it in.

**Comment by bloodearnest** [comment]
> > But what if they click it then change their minds?
> 
> This only makes sense if we have the reset button!

Well sure, but it's a unpleasent ux. IF they've already approved, and want to reject, and they have to do two clicks reset -> reject, rather than just straight to reject button which is *right there*

**Comment by ghickman** [comment]
Good point… could we ditch the reset button and let a user reset the state by clicking the selected state again?

**Comment by bloodearnest** [comment]
> Good point… could we ditch the reset button and let a user reset the state by clicking the selected state again?

I just didn't disable the button, so you go to any state from any state.

**Review by ghickman — APPROVED** [review]

**Pull request merged**
